services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel_order_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    ports:
      - 8000:8000
    depends_on:
      - db
      - mailpit
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:$(php artisan key:generate --show)
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=example@example.com
      - MAIL_FROM_NAME="Travel Order App"
  
  db:
    image: mysql:8.0
    container_name: travel_order_db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel_order
      MYSQL_USER: travel_order_user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - default

volumes:
  dbdata:
